wandb_version: 1

config:
  desc: null
  value:
  - /tmp/tmpch79y8we.yaml
seed:
  desc: null
  value: 0
encode_state:
  desc: null
  value: false
n_block:
  desc: null
  value: 1
n_embd:
  desc: null
  value: 64
n_head:
  desc: null
  value: 1
dec_actor:
  desc: null
  value: false
share_actor:
  desc: null
  value: false
callbacks:
  desc: null
  value: null
sb3_model_path:
  desc: null
  value: null
sb3_algo:
  desc: null
  value: null
step_difference:
  desc: null
  value: 1
gail:
  desc: null
  value: false
expert_data:
  desc: null
  value: null
gail_batch_size:
  desc: null
  value: 128
dis_input_len:
  desc: null
  value: null
gail_loss_target:
  desc: null
  value: null
gail_epoch:
  desc: null
  value: 5
gail_use_action:
  desc: null
  value: true
gail_hidden_size:
  desc: null
  value: 256
gail_layer_num:
  desc: null
  value: 3
gail_lr:
  desc: null
  value: 0.0005
data_dir:
  desc: null
  value: null
force_rewrite:
  desc: null
  value: false
collector_num:
  desc: null
  value: 1
input_data_dir:
  desc: null
  value: null
output_data_dir:
  desc: null
  value: null
worker_num:
  desc: null
  value: 1
sample_interval:
  desc: null
  value: 1
selfplay_api:
  desc: null
  value: Namespace(host='127.0.0.1', port=10086)
lazy_load_opponent:
  desc: null
  value: true
self_play:
  desc: null
  value: false
selfplay_algo:
  desc: null
  value: WeightExistEnemy
max_play_num:
  desc: null
  value: 2000
max_enemy_num:
  desc: null
  value: -1
exist_enemy_num:
  desc: null
  value: 0
random_pos:
  desc: null
  value: -1
build_in_pos:
  desc: null
  value: -1
use_amp:
  desc: null
  value: false
load_optimizer:
  desc: null
  value: false
use_joint_action_loss:
  desc: null
  value: true
frameskip:
  desc: null
  value: null
eval_render:
  desc: null
  value: false
terminal:
  desc: null
  value: current_terminal
distributed_type:
  desc: null
  value: sync
program_type:
  desc: null
  value: local
share_temp_dir:
  desc: null
  value: null
share_entry_script_path:
  desc: null
  value: null
learner_num:
  desc: null
  value: 1
fetch_num:
  desc: null
  value: 1
tmux_prefix:
  desc: null
  value: null
kill_all:
  desc: null
  value: false
namespace:
  desc: null
  value: default
mount_path:
  desc: null
  value: null
mount_name:
  desc: null
  value: null
persistent_volume_claim_name:
  desc: null
  value: null
disable_training:
  desc: null
  value: false
use_half_actor:
  desc: null
  value: false
algorithm_name:
  desc: null
  value: ppo
experiment_name:
  desc: null
  value: ppo
gpu_usage_type:
  desc: null
  value: auto
disable_cuda:
  desc: null
  value: false
cuda_deterministic:
  desc: null
  value: true
pytorch_threads:
  desc: null
  value: 1
n_rollout_threads:
  desc: null
  value: 100
n_eval_rollout_threads:
  desc: null
  value: 1
n_render_rollout_threads:
  desc: null
  value: 1
num_env_steps:
  desc: null
  value: 5000
user_name:
  desc: null
  value: openrl
wandb_entity:
  desc: null
  value: abl
disable_wandb:
  desc: null
  value: false
env_name:
  desc: null
  value: StarCraft2
scenario_name:
  desc: null
  value: default
num_agents:
  desc: null
  value: 3
num_enemies:
  desc: null
  value: 1
use_obs_instead_of_state:
  desc: null
  value: false
episode_length:
  desc: null
  value: 25
eval_episode_length:
  desc: null
  value: 200
max_episode_length:
  desc: null
  value: null
separate_policy:
  desc: null
  value: false
use_conv1d:
  desc: null
  value: false
stacked_frames:
  desc: null
  value: 1
use_stacked_frames:
  desc: null
  value: false
hidden_size:
  desc: null
  value: 64
layer_N:
  desc: null
  value: 1
activation_id:
  desc: null
  value: 1
use_popart:
  desc: null
  value: false
dual_clip_ppo:
  desc: null
  value: false
dual_clip_coeff:
  desc: null
  value: 3
use_valuenorm:
  desc: null
  value: true
use_feature_normalization:
  desc: null
  value: false
use_orthogonal:
  desc: null
  value: true
gain:
  desc: null
  value: 0.01
cnn_layers_params:
  desc: null
  value: null
use_maxpool2d:
  desc: null
  value: false
rnn_type:
  desc: null
  value: gru
rnn_num:
  desc: null
  value: 1
use_naive_recurrent_policy:
  desc: null
  value: false
use_recurrent_policy:
  desc: null
  value: true
recurrent_N:
  desc: null
  value: 1
data_chunk_length:
  desc: null
  value: 2
use_influence_policy:
  desc: null
  value: false
influence_layer_N:
  desc: null
  value: 1
use_attn:
  desc: null
  value: false
attn_N:
  desc: null
  value: 1
attn_size:
  desc: null
  value: 64
attn_heads:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.0
use_average_pool:
  desc: null
  value: true
use_attn_internal:
  desc: null
  value: true
use_cat_self:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0007
tau:
  desc: null
  value: 0.995
critic_lr:
  desc: null
  value: 0.0007
opti_eps:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0
bc_epoch:
  desc: null
  value: 2
ppo_epoch:
  desc: null
  value: 10
use_policy_vhead:
  desc: null
  value: false
use_clipped_value_loss:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.2
num_mini_batch:
  desc: null
  value: 1
mini_batch_size:
  desc: null
  value: null
policy_value_loss_coef:
  desc: null
  value: 0.5
entropy_coef:
  desc: null
  value: 0.01
value_loss_coef:
  desc: null
  value: 0.5
use_max_grad_norm:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 10
use_gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
use_proper_time_limits:
  desc: null
  value: false
use_huber_loss:
  desc: null
  value: true
use_value_active_masks:
  desc: null
  value: true
use_policy_active_masks:
  desc: null
  value: true
huber_delta:
  desc: null
  value: 10.0
use_adv_normalize:
  desc: null
  value: true
aux_epoch:
  desc: null
  value: 5
clone_coef:
  desc: null
  value: 1.0
use_single_network:
  desc: null
  value: false
use_linear_lr_decay:
  desc: null
  value: false
save_interval:
  desc: null
  value: 1
only_eval:
  desc: null
  value: false
log_interval:
  desc: null
  value: 10
log_each_episode:
  desc: null
  value: true
use_rich_handler:
  desc: null
  value: true
use_eval:
  desc: null
  value: false
eval_interval:
  desc: null
  value: 25
eval_episodes:
  desc: null
  value: 32
save_gifs:
  desc: null
  value: false
use_render:
  desc: null
  value: false
render_episodes:
  desc: null
  value: 5
ifi:
  desc: null
  value: 0.1
model_dir:
  desc: null
  value: null
save_dir:
  desc: null
  value: null
init_dir:
  desc: null
  value: null
run_dir:
  desc: null
  value: ./exp_results/
use_transmit:
  desc: null
  value: false
server_address:
  desc: null
  value: null
use_tlaunch:
  desc: null
  value: false
actor_num:
  desc: null
  value: 1
use_reward_normalization:
  desc: null
  value: false
buffer_size:
  desc: null
  value: 5000
popart_update_interval_step:
  desc: null
  value: 2
use_per:
  desc: null
  value: false
per_alpha:
  desc: null
  value: 0.6
per_beta_start:
  desc: null
  value: 0.4
per_eps:
  desc: null
  value: 1.0e-06
per_nu:
  desc: null
  value: 0.9
batch_size:
  desc: null
  value: 32
actor_train_interval_step:
  desc: null
  value: 2
train_interval_episode:
  desc: null
  value: 1
train_interval:
  desc: null
  value: 100
use_same_critic_obs:
  desc: null
  value: true
use_global_all_local_state:
  desc: null
  value: false
prev_act_inp:
  desc: null
  value: false
target_update:
  desc: null
  value: 10
var:
  desc: null
  value: 0.5
actor_lr:
  desc: null
  value: 0.001
auto_alph:
  desc: null
  value: false
alpha_value:
  desc: null
  value: 0.2
alpha_lr:
  desc: null
  value: 0.0002
use_soft_update:
  desc: null
  value: true
hard_update_interval_episode:
  desc: null
  value: 200
num_random_episodes:
  desc: null
  value: 5
epsilon_start:
  desc: null
  value: 1.0
epsilon_finish:
  desc: null
  value: 0.05
epsilon_anneal_time:
  desc: null
  value: 5000
use_double_q:
  desc: null
  value: true
hypernet_layers:
  desc: null
  value: 2
mixer_hidden_dim:
  desc: null
  value: 32
hypernet_hidden_dim:
  desc: null
  value: 64
target_action_noise_std:
  desc: null
  value: 0.2
data_path:
  desc: null
  value: null
env:
  desc: null
  value: Namespace(args={})
model_path:
  desc: null
  value: null
use_share_model:
  desc: null
  value: false
reward_class:
  desc: null
  value: Namespace(id=None, args={})
vec_info_class:
  desc: null
  value: Namespace(id=None, args={})
eval_metrics:
  desc: null
  value: []
disable_update_enemy:
  desc: null
  value: false
least_win_rate:
  desc: null
  value: 0.5
recent_list_max_len:
  desc: null
  value: 100
latest_weight:
  desc: null
  value: 0.5
newest_pos:
  desc: null
  value: 1
newest_weight:
  desc: null
  value: 0.5
use_deepspeed:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
use_offload:
  desc: null
  value: false
use_fp16:
  desc: null
  value: false
learner_n_rollout_threads:
  desc: null
  value: 100
rnn_hidden_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.9.4
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715016849.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.9.4
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
